#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='micro'
export VISUAL='micro'

export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $HOME/.cargo/bin
  $HOME/.local/bin
  $path
)

if [[ "$OSTYPE" == darwin* ]]; then
  path=(
    $path
    $HOME/bin
    $HOME/Library/Python/2.7/bin
    $HOME/Library/Python/3.7/bin
    $HOME/.gem/ruby/2.3.0/bin
  )
fi

#
# Less
#

export LESSQUIET=1
export LESSCOLORIZER='pygmentize'

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -S'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe.sh] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe.sh] %s 2>&-"
elif (( $#commands[(i)lesspipe] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe] %s 2>&-"
fi
