#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ "$OSTYPE" == linux* ]]; then
  if [[ -z "${SSH_AUTH_SOCK}" ]]; then
    export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
  fi
  if [[ -z "${SSH_ASKPASS}" ]]; then
    export SSH_ASKPASS="/usr/bin/ksshaskpass"
  fi

  export QT_ASSUME_STDERR_HAS_CONSOLE=1
fi

export NINJAJOBS=-j8

export CARGO_HOME="$HOME/.cargo"

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

