#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$OSTYPE" == linux* ]]; then
  alias open='xdg-open'
  alias cp='cp --reflink=auto'
fi

alias gdb='gdb -quiet'

export ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;&|'
export ZLE_SPACE_SUFFIX_CHARS=$'&|'

bindkey "^[[5~" history-beginning-search-backward
bindkey "^[[6~" history-beginning-search-forward

if [[ "$OSTYPE" == linux* && -f /etc/grc.zsh ]]; then
  . /etc/grc.zsh
fi
